---
- hosts: k8s_nodes
  become: yes
  tasks:
    - name: Unzip artifacts
      unarchive:
        src: /opt/nova/ZKP-Microsoft-Nova_pilot.zip
        dest: /opt/nova/
        creates: /opt/nova/nova-rollup_20240609.tar

    - name: Load Docker images
      command: docker load -i /opt/nova/nova-rollup_20240609.tar

    - name: Load smart contract tarball
      unarchive:
        src: /opt/nova/nova-smartcontract_20240615.tar.gz
        dest: /opt/nova/contracts/

    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Install Foundry
      shell: |
        curl -L https://foundry.paradigm.xyz | bash
        foundryup

    - name: Generate keypairs
      shell: cast wallet new
      register: keypairs

    - name: Save keypairs to file
      copy:
        content: "{{ keypairs.stdout }}"
        dest: /opt/nova/keypairs.txt

    - name: Deploy smart contracts
      shell: |
        source /opt/nova/contracts/example.env
        cd /opt/nova/contracts
        yarn
        npx hardhat compile
        npx hardhat run script/hardhat/deploy-common.ts --network pilot
        npx hardhat run script/hardhat/deploy-wcbdc.ts --network pilot
        npx hardhat run script/hardhat/deploy-rcbdc.ts --network pilot

    - name: Customize Helm configuration
      template:
        src: helm/bcb.yaml.j2
        dest: /opt/nova/bcb.yaml

    - name: Deploy Nova Rollup using Helm
      shell: |
        helm install -n nova -f /opt/nova/bcb.yaml nova-bcb ./nova-zkp/

